extern crate alloc;

use embassy_time::{Duration, Instant};
use fixed::types::I16F16;
use hashbrown::HashMap;
use heapless::Vec;
use serde::{Deserialize, Serialize};
use shared::MdsResult;

// Generated by build.rs: 10^((-56 - rssi) / 25.0) as I16F16 bits for rssi in -128..=127
include!(concat!(env!("OUT_DIR"), "/rssi_to_dist.rs"));

pub const MAX_SWARM_SIZE: usize = 10;
const NEIGHBOR_EXPIRY: Duration = Duration::from_secs(10);

const EMA_ALPHA: I16F16 = I16F16::from_bits(19661); // ≈ 0.3
const ONE_MINUS_EMA: I16F16 = I16F16::from_bits(45875); // ≈ 0.7
const SPIKE_THRESHOLD: I16F16 = I16F16::from_bits(786_432); // 12.0
const WINDOW_SIZE: usize = 8;

fn dist_from_rssi(rssi: i8) -> I16F16 {
    I16F16::from_bits(RSSI_TO_DIST_BITS[(rssi as i32 + 128) as usize])
}

#[derive(Debug, Copy, Clone, Serialize, Deserialize)]
struct RssiWindow {
    buf: [I16F16; WINDOW_SIZE],
    head: usize,
    sum: I16F16,
    len: usize,
}

impl RssiWindow {
    fn new(initial: I16F16) -> Self {
        let mut buf = [I16F16::ZERO; WINDOW_SIZE];
        buf[0] = initial;
        RssiWindow {
            buf,
            head: 1,
            sum: initial,
            len: 1,
        }
    }

    /// Push a new value; returns the updated window mean.
    fn push(&mut self, value: I16F16) -> I16F16 {
        if self.len < WINDOW_SIZE {
            // still filling up, just append
            self.buf[self.head] = value;
            self.sum += value;
            self.len += 1;
            self.head = (self.head + 1) % WINDOW_SIZE;
        } else {
            // overwrite oldest slot
            let oldest = self.buf[self.head];
            self.sum += value - oldest;
            self.buf[self.head] = value;
            self.head = (self.head + 1) % WINDOW_SIZE;
        }
        self.mean()
    }

    fn mean(&self) -> I16F16 {
        self.sum / I16F16::from_num(self.len as i32)
    }
}

#[derive(Debug, Copy, Clone, Serialize, Deserialize)]
pub struct State {
    pub rssi: i8,
    pub ema_rssi: I16F16, // raw latest RSSI (for display/debug)
    window: RssiWindow,   // EMA-smoothed, spike-filtered value
    pub dist: I16F16,     // sliding window for spike reference
    pub count: u32,
}

impl State {
    #[must_use]
    pub fn from_dist(dist: I16F16) -> State {
        State {
            rssi: 0,
            ema_rssi: I16F16::ZERO,
            window: RssiWindow::new(I16F16::ZERO),
            dist,
            count: 0,
        }
    }

    #[must_use]
    pub fn new(rssi: i8) -> State {
        let f = I16F16::from_num(rssi);
        State {
            rssi,
            ema_rssi: f,
            window: RssiWindow::new(f),
            dist: dist_from_rssi(rssi),
            count: 1,
        }
    }

    pub fn update(&mut self, rssi: i8) {
        self.rssi = rssi;
        self.count += 1;

        let raw = I16F16::from_num(rssi);
        let win_mean = self.window.mean();

        // If the new sample is a outlier vs. the recent window mean,
        // clamp it toward the mean rather than discarding it entirely.
        // Discarding causes stalls; clamping keeps the filter responsive
        // while suppressing the spike's magnitude.
        let filtered = if (raw - win_mean).abs() > SPIKE_THRESHOLD {
            // Clamp to the boundary: preserve direction but limit excursion
            let sign = if raw > win_mean {
                I16F16::ONE
            } else {
                -I16F16::ONE
            };
            win_mean + sign * SPIKE_THRESHOLD
        } else {
            raw
        };

        self.window.push(raw);
        self.ema_rssi = EMA_ALPHA * filtered + ONE_MINUS_EMA * self.ema_rssi;
        // Truncate smoothed RSSI to integer for lookup (floor toward -∞)
        let ema_int = (self.ema_rssi.to_bits() >> 16).clamp(-128, 127) as i8;
        self.dist = dist_from_rssi(ema_int);
    }
}

#[derive(Debug)]
pub struct NodeState {
    pub mac: [u8; 6],
    pub neighbours: HashMap<[u8; 6], HashMap<[u8; 6], State>>,
    pub mds: MdsResult,
    pub estimated_distances: HashMap<[u8; 6], f32>,
    last_seen: HashMap<[u8; 6], Instant>,
}

impl NodeState {
    pub fn new(mac: [u8; 6]) -> NodeState {
        let mut state = NodeState {
            mac,
            neighbours: HashMap::new(),
            mds: Vec::default(),
            estimated_distances: HashMap::new(),
            last_seen: HashMap::new(),
        };
        state.neighbours.insert(mac, HashMap::new());
        state
    }

    pub fn register_neighbour(&mut self, mac: [u8; 6]) {
        self.neighbours.insert(mac, HashMap::new());
    }

    /// mehod might panic if the node is not in its own hash map
    // method that updates the measurement from the current node to the node that it just received a
    // broadcast from
    // src = own node, address = node we received it from
    pub fn update_distance_from_self(&mut self, self_addr: [u8; 6], other_addr: [u8; 6], rssi: i8) {
        self.last_seen.insert(other_addr, Instant::now());
        let state_map = self
            .neighbours
            .get_mut(&self_addr)
            .expect("Node's mac address should have been set upon initialization");
        state_map
            .entry(other_addr)
            .and_modify(|state| state.update(rssi))
            .or_insert_with(|| State::new(rssi));
    }

    pub fn expire_stale(&mut self) {
        let now = Instant::now();
        let expired: Vec<[u8; 6], MAX_SWARM_SIZE> = self
            .neighbours
            .keys()
            .filter(|&&mac| {
                mac != self.mac
                    && self
                        .last_seen
                        .get(&mac)
                        .and_then(|&t| now.checked_duration_since(t))
                        .is_none_or(|elapsed| elapsed > NEIGHBOR_EXPIRY)
            })
            .copied()
            .collect();

        for mac in &expired {
            self.neighbours.remove(mac);
            self.last_seen.remove(mac);
        }

        if !expired.is_empty() {
            self.mds.clear();
        }
    }

    /// Stores TC-propagated distances for `origin`'s direct neighbours.
    /// Uses `or_insert_with` so direct Hello measurements are never overwritten.
    pub fn update_tc_neighbor_distances(
        &mut self,
        origin: [u8; 6],
        neighbors: &Vec<[u8; 6], MAX_SWARM_SIZE>,
        distances: &Vec<I16F16, MAX_SWARM_SIZE>,
    ) {
        let map = self.neighbours.entry(origin).or_insert_with(HashMap::new);
        for (mac, &dist) in neighbors.iter().zip(distances.iter()) {
            if dist < I16F16::MAX {
                map.entry(*mac).or_insert_with(|| State::from_dist(dist));
            }
        }
    }

    pub fn update_estimated_distances(&mut self, estimates: HashMap<[u8; 6], f32>) {
        self.estimated_distances = estimates;
    }

    // method that updates the matrix of measurements that a node has of its neighbours
    pub fn update_measurements_from_neighbor(
        &mut self,
        mac: [u8; 6],
        measurements: HashMap<[u8; 6], State>,
    ) {
        self.neighbours.insert(mac, measurements);
    }

    pub fn get_ordered_mac_addresses(&self) -> Vec<[u8; 6], MAX_SWARM_SIZE> {
        let mut vec: Vec<[u8; 6], MAX_SWARM_SIZE> = Vec::new();
        self.neighbours.keys().for_each(|&node| {
            let _ = vec.push(node);
        });
        for &mac in self.estimated_distances.keys() {
            if !vec.contains(&mac) {
                let _ = vec.push(mac);
            }
        }
        // Mac addresses are unique, so this is fine (more performant then regular sort)
        vec.sort_unstable();
        vec
    }

    // method that generates adjacency matrix to be used for MDS
    pub fn neighbour_matrix(&self) -> Vec<Vec<I16F16, MAX_SWARM_SIZE>, MAX_SWARM_SIZE> {
        let vec = self.get_ordered_mac_addresses();
        let own_mac = self.mac;
        vec.iter()
            .map(|node| {
                let direct = self.neighbours.get(node);
                vec.iter()
                    .map(|n| {
                        direct
                            .and_then(|nbrs| nbrs.get(n))
                            .map(|state| state.dist)
                            .unwrap_or_else(|| {
                                if node == n {
                                    I16F16::ZERO
                                } else if *node == own_mac {
                                    self.estimated_distances
                                        .get(n)
                                        .copied()
                                        .map(I16F16::from_num)
                                        .unwrap_or(I16F16::MAX)
                                } else if *n == own_mac {
                                    self.estimated_distances
                                        .get(node)
                                        .copied()
                                        .map(I16F16::from_num)
                                        .unwrap_or(I16F16::MAX)
                                } else {
                                    self.neighbours
                                        .get(n)
                                        .and_then(|nbrs| nbrs.get(node))
                                        .map(|s| s.dist)
                                        .unwrap_or(I16F16::MAX)
                                }
                            })
                    })
                    .collect()
            })
            .collect()
    }

    pub fn get_ordered_distances(&self) -> Vec<Vec<I16F16, MAX_SWARM_SIZE>, MAX_SWARM_SIZE> {
        let vec = self.get_ordered_mac_addresses();
        let own_mac = self.mac;
        vec.iter()
            .map(|node| {
                let direct = self.neighbours.get(node);
                vec.iter()
                    .map(|n| {
                        direct
                            .and_then(|nbrs| nbrs.get(n))
                            .map(|state| state.dist)
                            .unwrap_or_else(|| {
                                if node == n {
                                    I16F16::ZERO
                                } else if *node == own_mac {
                                    self.estimated_distances
                                        .get(n)
                                        .copied()
                                        .map(I16F16::from_num)
                                        .unwrap_or(I16F16::MAX)
                                } else if *n == own_mac {
                                    self.estimated_distances
                                        .get(node)
                                        .copied()
                                        .map(I16F16::from_num)
                                        .unwrap_or(I16F16::MAX)
                                } else {
                                    self.neighbours
                                        .get(n)
                                        .and_then(|nbrs| nbrs.get(node))
                                        .map(|s| s.dist)
                                        .unwrap_or(I16F16::MAX)
                                }
                            })
                    })
                    .collect()
            })
            .collect()
    }
}
