[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c3"

[env]
ESP_LOG="info"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

[alias]
build-firmware = "build -p esp32-firmware --target riscv32imc-unknown-none-elf"
run-firmware = "run -p esp32-firmware --target riscv32imc-unknown-none-elf"
build-telemetry = "build -p telemetry-server"
run-telemetry = "run -p telemetry-server"

# target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["core"]
