name: Rust CI

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install Rust target
        run: rustup target add riscv32imc-unknown-none-elf

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --verbose

      - name: Test
        run: cargo test --verbose

      - name: Clippy
        run: cargo clippy --all-features -- \
                -W clippy::all \
                -W clippy::pedantic
